export const worksheetCols = [
    { header: "Start Month", key: "start" },
    { header: "End Month", key: "end" },
    { header: "Due Date", key: "dueDate" },
    { header: "Order ID", key: "payment.orderId" },
    { header: "Status", key: "status" },
    { header: "Order Payment method", key: "payment.paymentMethodId" },
    { header: "Sample Size Cost Per Month - VND", key: "sampleSizeCostPerMonth" },
    { header: "Sample Size Cost Per Month - USD", key: "sampleSizeCostPerMonthUSD" },
    { header: "Custom Question Cost Per Month - VND", key: "customQuestionCostPerMonth" },
    { header: "Custom Question Cost Per Month - USD", key: "customQuestionCostPerMonthUSD" },
    { header: "VAT", key: "vat" },
    { header: "VAT USD", key: "vatUSD" },
    { header: "Total Amount - VND", key: "totalAmount" },
    { header: "Total Amount - USD", key: "totalAmountUSD" },
    { header: "VAT Rate", key: "systemConfig.vat" },
    { header: "USDToVNDRate", key: "systemConfig.usdToVND" },
    { header: "Created Time", key: "createdAt" },
    { header: "Completed Time", key: "payment.completedDate" },
];