export const worksheetCols = [
  { header: "Order ID", key: "orderId" },
  { header: "Order Status", key: "status" },
  { header: "Order Payment method", key: "paymentMethodId" },
  { header: "Order Sample Size Cost - VND", key: "sampleSizeCost" },
  { header: "Order Sample Size Cost - USD", key: "sampleSizeCostUSD" },
  { header: "Order Custom Question Cost - VND", key: "customQuestionCost" },
  { header: "Order Custom Question Cost - USD", key: "customQuestionCostUSD" },
  { header: "Order Eye Tracking Cost - VND", key: "eyeTrackingSampleSizeCost" },
  { header: "Order Eye Tracking Cost - USD", key: "eyeTrackingSampleSizeCostUSD" },
  { header: "Order VAT", key: "vat" },
  { header: "Order VAT USD", key: "vatUSD" },
  { header: "Order Total Amount - VND", key: "totalAmount" },
  { header: "Order Total Amount - USD", key: "totalAmountUSD" },
  { header: "Order VAT Rate", key: "vatRate" },
  { header: "Order USDToVNDRate", key: "usdToVNDRate" },
  { header: "Order Created Time", key: "createdAt" },
  { header: "Order Completed Time", key: "completedDate" },
  { header: "Order Cancel Time", key: "cancelledDate" },
  { header: "User ID", key: "user.id" },
  { header: "User Fullname", key: "user.fullName" },
  { header: "User Email", key: "user.email" },
  { header: "User Phone", key: "user.phone" },
  { header: "Project ID", key: "project.id" },
  { header: "Project Name", key: "project.name" },
  { header: "Invoice_Fullname", key: "fullName" },
  { header: "Invoice_CompanyName", key: "companyName" },
  { header: "Invoice_CompanyAddress", key: "companyAddress" },
  { header: "Invoice_Email", key: "email" },
  { header: "Invoice_Phone", key: "phone" },
  { header: "Invoice_Country", key: "country.name" },
  { header: "Invoice_TaxCode", key: "taxCode" },
  { header: "Onepay_Success_MerchTxnRef", key: "onepays.vpc_MerchTxnRef" },
  { header: "Onepay_Success_OrderInfo", key: "onepays.vpc_OrderInfo" },
  { header: "Onepay_Success_Amount", key: "onepays.amount" },
  { header: "Onepay_Success_TicketNo", key: "onepays.vpc_TicketNo" },
];